/**
 * Emits the two consumable artifacts from `tokens.json`:
 *
 * - `tokens.css`    — every token as a CSS custom property. Colors are written twice: the `light`
 *                     values on `:root` and the `dark` values inside `@media (prefers-color-scheme:
 *                     dark)`, which is the whole of the app's theme switching (design spec §8).
 * - `tailwind.preset.js` — a Tailwind preset whose scale values are `var(--wl-…)` references, never
 *                     literals. That indirection is what makes the media query above enough: a
 *                     `bg-background` utility resolves through the variable, so the same class is
 *                     correct in both themes and `apps/web` hardcodes nothing (§14.1).
 *
 * Both outputs are committed. Regenerate with `pnpm -F @workledger/tokens build`; the script is
 * deterministic, so a drifted commit shows up as a dirty tree in CI.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const PKG = new URL("../", import.meta.url);
const PREFIX = "wl";

/** Groups whose members are theme-independent, and the Tailwind scale each one feeds. */
const SCALES = [
  { path: ["spacing"], varPart: "spacing", tailwindKey: "spacing" },
  { path: ["radius"], varPart: "radius", tailwindKey: "borderRadius" },
  { path: ["type", "size"], varPart: "font-size", tailwindKey: "fontSize" },
  { path: ["type", "family"], varPart: "font-family", tailwindKey: "fontFamily" },
];

/** Walks a `SCALES` path into the token tree. */
function group(tokens, path) {
  return path.reduce((node, key) => {
    if (!node?.[key]) throw new Error(`no token group at "${path.join(".")}"`);
    return node[key];
  }, tokens);
}

/**
 * Flattens one W3C token group into `[name, value]` pairs. Only leaves — an object carrying a
 * `$value` — are tokens; `$type`/`$description` siblings are metadata and are skipped.
 */
function leaves(group) {
  return Object.entries(group)
    .filter(([name, node]) => !name.startsWith("$") && node && typeof node === "object")
    .map(([name, node]) => {
      if (typeof node.$value !== "string") {
        throw new Error(`token "${name}" has no string $value — nested groups are not supported`);
      }
      return [name, node.$value];
    });
}

const tokens = JSON.parse(readFileSync(new URL("tokens.json", PKG), "utf8"));

const lightColors = leaves(tokens.color.light);
const darkColors = leaves(tokens.color.dark);
const lightNames = lightColors.map(([name]) => name);
const darkNames = darkColors.map(([name]) => name);
// A role present in one theme and not the other would resolve to the light value in dark mode —
// silently, and only for that one utility. Fail the build instead.
if (lightNames.join() !== darkNames.join()) {
  throw new Error(
    `color.light and color.dark must declare the same roles in the same order; ` +
      `light has [${lightNames.join(", ")}], dark has [${darkNames.join(", ")}]`,
  );
}

const colorVar = (name) => `--${PREFIX}-color-${name}`;
const scaleVar = (varPart, name) => `--${PREFIX}-${varPart}-${name}`;
const declare = (pairs) => pairs.map(([name, value]) => `  ${name}: ${value};`).join("\n");

const scaleBlocks = SCALES.map(({ path, varPart }) =>
  declare(leaves(group(tokens, path)).map(([name, value]) => [scaleVar(varPart, name), value])),
);

const css = `/* Generated by scripts/build-preset.mjs from tokens.json — do not edit by hand. */
:root {
  color-scheme: light dark;

${declare(lightColors.map(([name, value]) => [colorVar(name), value]))}

${scaleBlocks.join("\n\n")}
}

@media (prefers-color-scheme: dark) {
  :root {
${declare(darkColors.map(([name, value]) => [colorVar(name), value]))}
  }
}
`;

const entries = (pairs) => `{\n${pairs.map(([k, v]) => `        ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n")}\n      }`;

const preset = `/* Generated by scripts/build-preset.mjs from tokens.json — do not edit by hand. */
/** @type {import("tailwindcss").Config} */
export default {
  theme: {
    extend: {
      colors: ${entries(lightColors.map(([name]) => [name, `var(${colorVar(name)})`]))},
${SCALES.map(
  ({ path, varPart, tailwindKey }) =>
    `      ${tailwindKey}: ${entries(
      leaves(group(tokens, path)).map(([name]) => [name, `var(${scaleVar(varPart, name)})`]),
    )},`,
).join("\n")}
    },
  },
};
`;

for (const [file, contents] of [
  ["tokens.css", css],
  ["tailwind.preset.js", preset],
]) {
  const target = new URL(file, PKG);
  writeFileSync(target, contents);
  console.log(`tokens: wrote ${fileURLToPath(target)}`);
}
